CREATE DATABASE test CHARACTER SET = UTF8 COLLATE = UTF8_BIN;
USE test;
CREATE TABLE roles(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
label VARCHAR (100)
)